spring.application.name=gestionUser

### DATABASE ###
spring.datasource.url=jdbc:mysql://localhost:3306/baladna?&createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=

### JPA / HIBERNATE ###
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

### SERVER ###
server.port=8081

### LOGGING ###
logging.level.org.springframework.security=DEBUG
logging.level.tn.esprit.spring.baladna.marketplace.ai=DEBUG

### AUTRE ###
spring.main.allow-bean-definition-overriding=true
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

### FILE UPLOAD ###
spring.servlet.multipart.max-file-size=15MB
spring.servlet.multipart.max-request-size=15MB
spring.jackson.deserialization.fail-on-unknown-properties=false

### HUGGING FACE API (GRATUIT) ###
huggingface.api.key=mykey
openai.api.key=votre_cle_openai_ici

### EMAIL CONFIGURATION ###
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=khefifi.salma@gmail.com
spring.mail.password=hzmw dsbn jojw awzg

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

### ADMIN EMAIL ###
app.admin.email=admin@baladna.com


stripe.secret.key=mykey
cloudinary.cloud-name=dwsacemju
cloudinary.api-key=mykey
cloudinary.api-secret=mykey

### photo market###
unsplash.access.key=mykey